### ISSUE TITLE
bug(dropbot): static files not included in packaged distribution

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-exe#1]
# Problem

The following exception occurred when trying to access a static HTML template file from the `dropbot` package:

```python
2018-08-24 08:24:01.825 [ERROR:dropbot_plugin.<lambda>]: Error executing DropBot self tests.
Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\MicroDrop\app-2.27.0-rc0alpha0\app\etc\microdrop\plugins\enabled\dropbot_plugin\__init__.py", line 288, in _wrapped
  File "C:\Users\chris\AppData\Local\MicroDrop\app-2.27.0-rc0alpha0\app\etc\microdrop\plugins\enabled\dropbot_plugin\__init__.py", line 265, in _wrapped
  File "C:\Users\chris\AppData\Local\MicroDrop\app-2.27.0-rc0alpha0\app\etc\microdrop\plugins\enabled\dropbot_plugin\__init__.py", line 341, in _wrapped
  File "C:\Users\chris\AppData\Local\MicroDrop\app-2.27.0-rc0alpha0\app\etc\microdrop\plugins\enabled\dropbot_plugin\__init__.py", line 955, in run_all_tests
  File "dropbot\self_test.pyc", line 762, in generate_report
  File "pkgutil.pyc", line 591, in get_data
IOError: [Errno 0] Error: 'dropbot\\static\\templates\\SelfTestTemplate.html5'
```

# Cause

The `py2exe` build is not including the `dropbot/static` files in the build.

**Comment by cfobel** [comment]
Fixed by [adding references to the the static files `JsonSchemaCollector.copy_extensions()` method][1].

[1]: https://github.com/sci-bots/microdrop-exe/blob/7b1d74f4e3d4c1819f795749e49094299a40e733/setup.py#L155-L158

**Comment by cfobel** [comment]
Fixed by [adding references to the the static files `JsonSchemaCollector.copy_extensions()` method][1].

[1]: https://github.com/sci-bots/microdrop-exe/blob/7b1d74f4e3d4c1819f795749e49094299a40e733/setup.py#L155-L158
